require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

def ccache_enabled?(podfile_properties)
  # Environment variable takes precedence
  return ENV['USE_CCACHE'] == '1' if ENV['USE_CCACHE']
  
  # Fall back to Podfile properties
  podfile_properties['apple.ccacheEnabled'] == 'true'
end

ENV['RCT_NEW_ARCH_ENABLED'] ||= '0' if podfile_properties['newArchEnabled'] == 'false'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] ||= podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']
ENV['RCT_USE_RN_DEP'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
ENV['RCT_USE_PREBUILT_RNCORE'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'

prepare_react_native_project!

target 'Trax' do
  use_expo_modules!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'node',
      '--no-warnings',
      '--eval',
      'require(\'expo/bin/autolinking\')',
      'expo-modules-autolinking',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => ccache_enabled?(podfile_properties),
    )
    # Bump all pods with old deployment targets to silence Xcode warnings
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        current = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
        if current && current.to_f < 16.0
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
        end
        if target.name == 'fmt'
          config.build_settings['GCC_CXX_LANGUAGE_STANDARD'] = 'gnu++17'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited) COCOAPODS=1 FMT_USE_CONSTEVAL=0'
        end
      end
    end
    # Patch fmt xcconfig files to disable consteval (broken with Apple clang + C++20)
    # Patch fmt to disable consteval (broken with Apple clang + iOS deployment target mismatch)
    fmt_base = "#{installer.sandbox.root}/fmt/include/fmt/base.h"
    if File.exist?(fmt_base)
      FileUtils.chmod(0644, fmt_base)
      content = File.read(fmt_base)
      content = content.gsub('#  define FMT_USE_CONSTEVAL 1', '#  define FMT_USE_CONSTEVAL 0')
      File.write(fmt_base, content)
    end
    Dir.glob("#{installer.sandbox.root}/Target Support Files/fmt/*.xcconfig").each do |xcconfig_path|
      content = File.read(xcconfig_path)
      content = content.gsub('CLANG_CXX_LANGUAGE_STANDARD = c++20', 'CLANG_CXX_LANGUAGE_STANDARD = gnu++17')
      content = content.gsub(
        'GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1',
        'GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1 FMT_USE_CONSTEVAL=0'
      )
      File.write(xcconfig_path, content)
    end
    # Patch RCT-Folly to disable coroutines (coro headers not bundled in pod)
    Dir.glob("#{installer.sandbox.root}/Target Support Files/RCT-Folly/*.xcconfig").each do |xcconfig_path|
      content = File.read(xcconfig_path)
      content = content.gsub('GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1', 'GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1 FOLLY_HAS_COROUTINES=0')
      File.write(xcconfig_path, content)
    end
    folly_portability = "#{installer.sandbox.root}/RCT-Folly/folly/Portability.h"
    if File.exist?(folly_portability)
      FileUtils.chmod(0644, folly_portability)
      content = File.read(folly_portability)
      content = content.gsub('#define FOLLY_HAS_COROUTINES 1', '#define FOLLY_HAS_COROUTINES 0 // patched: coro headers not in pod')
      File.write(folly_portability, content)
    end
  end
end
